!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 2048
  - - buffer_size
    - 1000000
  - - env_wrapper
    - - sb3_contrib.common.wrappers.TimeFeatureWrapper
  - - gamma
    - 0.95
  - - goal_selection_strategy
    - future
  - - learning_rate
    - 0.001
  - - model_class
    - tqc
  - - n_sampled_goal
    - 4
  - - n_timesteps
    - 1000000.0
  - - online_sampling
    - true
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict(n_critics=2, net_arch=[512, 512, 512])
  - - tau
    - 0.05
