!!python/object/apply:collections.OrderedDict
- - - delta_std
    - 0.2
  - - learning_rate
    - 0.018
  - - n_delta
    - 4
  - - n_envs
    - 8
  - - n_timesteps
    - 500000.0
  - - n_top
    - 1
  - - normalize
    - dict(norm_obs=True, norm_reward=False)
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict(net_arch=[16])
  - - zero_policy
    - false
