!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 256
  - - buffer_size
    - 1000000
  - - ent_coef
    - auto
  - - gamma
    - 0.99
  - - gradient_steps
    - 1
  - - learning_rate
    - lin_7.3e-4
  - - learning_starts
    - 10000
  - - n_timesteps
    - 2000000.0
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict(net_arch=[400, 300])
  - - tau
    - 0.01
  - - train_freq
    - 1
